{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cabure.fullname" . }}
  namespace: {{ include "cabure.namespace" . }}
  labels:
    {{- include "cabure.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "cabure.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 8080
        - port: 8081
  egress:
    - {}
{{- end }}
