{{- if gt (int .Values.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cabure.fullname" . }}
  namespace: {{ include "cabure.namespace" . }}
  labels:
    {{- include "cabure.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "cabure.selectorLabels" . | nindent 6 }}
{{- end }}
