apiVersion: gitops.cabure.io/v1alpha1
kind: GitApplication
metadata:
  name: dragonfly
  namespace: dragonfly-operator-system
spec:
  source:
    repository: git@github.com:GreedyKomodoDragon/PuffinNest.git
    revision: main
    path: infra/database-charts/dragonfly
    secretRef:
      name: dragonfly-operator-git-ssh
  destination:
    namespace: dragonfly
  render:
    type: helm
    helm:
      releaseName: dragonfly
      valuesFiles:
        - infra/dev-overrides/dragonfly-dev.yaml
  interval: 1m0s
  prune: true
  takeoverExistingResources: true
